// Point d'entrée du DS FDC. Les consommateurs importent depuis 'fdc-ui'.
// Consommé en dépendance git (github:Meridian-Synergy/fdc-ui), transpilé par le
// consommateur (pas de build/publish npm).
export { default as FdcButton } from './components/FdcButton/FdcButton.vue'
export { default as FdcLogo } from './components/FdcLogo/FdcLogo.vue'
export { default as FdcInput } from './components/FdcInput/FdcInput.vue'
export { default as FdcField } from './components/FdcField/FdcField.vue'
export { default as FdcCard } from './components/FdcCard/FdcCard.vue'
export { default as FdcAlert } from './components/FdcAlert/FdcAlert.vue'
export { default as FdcContainer } from './components/FdcContainer/FdcContainer.vue'
export { default as FdcSpinner } from './components/FdcSpinner/FdcSpinner.vue'
export { default as FdcLoadingState } from './components/FdcLoadingState/FdcLoadingState.vue'
export { default as FdcThemeToggle } from './components/FdcThemeToggle/FdcThemeToggle.vue'
export { default as FdcTextSizeToggle } from './components/FdcTextSizeToggle/FdcTextSizeToggle.vue'
export { default as FdcLocaleSwitcher } from './components/FdcLocaleSwitcher/FdcLocaleSwitcher.vue'
export { default as FdcCookieConsent } from './components/FdcCookieConsent/FdcCookieConsent.vue'
export { default as FdcInstallBanner } from './components/FdcInstallBanner/FdcInstallBanner.vue'
export { default as FdcOAuthButtons } from './components/FdcOAuthButtons/FdcOAuthButtons.vue'
export { default as FdcDataTable } from './components/FdcDataTable/FdcDataTable.vue'
export type { FdcColumn } from './components/FdcDataTable/types'
